### ISSUE TITLE
Rails 4.2 compatibility

### ISSUE THREAD

**Issue by daniel-rikowski** [clemens/delocalize#74]
Once again the new Rails version is incompatible with delocalize, because the internal API regarding type casts of attributes has changed. (for the better imho)

I've spend some time on this and created a monkey patch which makes the current 0.4 release work with Rails 4.2. https://gist.github.com/daniel-rikowski/fd09dc2cc82ce28e7986

I'm not sure if this works 100%, but at least all my tests are green.

**Comment by clemens** [comment]
Sorry it took me a while to get back to this.

I've reviewed your monkeypatch. I don't like it – and this has nothing to do with your code. It's just what I said in my first comment and what I've said in other places: delocalize in this form (i.e. the 0.x branches) sucks – in fact, it sucks a lot. Every small-ish change to Rails internals (be it ActionView or ActiveRecord) effectively requires some new monkeypatching. It shouldn't be like that – but I see no way preventing this with delocalize staying at the same layer as it currently is (writing done in ActiveRecord, reading done in ActionView).

I'd like to finish up the work that I've begun with delocalize 1.0 – which operates at the controller and view level and gets much less involved with Rails internals (in fact, currently it's not involved with internals at all). Yes, there's a bit more implementation work involved – but I think that's a healthy thing: Back when I wrote the original code, "magic" was considered a good thing in the community and we liked stuff like "acts_as_list" that you could just add as a gem and it would dump a million methods into every object. Nowadays, we know that's not good – so delocalize shouldn't do it either, even if that means a bit more code because things are more explicit.

@daniel-rikowski Do you, by any chance, have the possibility to branch off your project and convert it to delocalize 1.0 and report any issues that you might have? Also, an upgrade guide would be tremendously helpful. I would do it myself but the thing is: I'm not using delocalize in any current project – so there's no "real life" project to test things out.

Let me know. Thanks!
- C.

**Comment by MSNexploder** [comment]
A quick heads up.

I converted a project of mine to 1.0 beta and everything works as expected.
Had to use @jackiig branch because of this problem: https://github.com/clemens/delocalize/pull/72

**Comment by daniel-rikowski** [comment]
I'm in the process of converting my application, but I was biten by https://github.com/svenfuchs/i18n/issues/104 (In my app the delimiter and separator are defined in a fallback locale)

I created a pull request (https://github.com/svenfuchs/i18n/pull/304) to fix this long-standing bug. (Earliest report was 2011!)

**Comment by daniel-rikowski** [comment]
Any news about #72 and #75 (75 also fixes 72)? For me these are the only problems keeping me from using 1.0-beta of delocalize.

**Comment by clemens** [comment]
@MSNexploder Great news, thanks for reporting in! :)

@daniel-rikowski I've merged #72 and commented on #75. I can merge it later today if you prep it.

**Comment by sobrinho** [comment]
@clemens I've been using delocalise 1-0-beta on production for several months now and everything is fine.

Can you release a gem to avoid cloning the repository and have faster deploys?  Thanks! :)

**Comment by clemens** [comment]
I'd love to finally get this out. :) I'l need to have a look at the open PRs/issues to figure out if everything's been addressed directly (issue fixed) or indirectly (issue irrelevant because of the architecture change). If you have time to take a look, that would be tremendously helpful. :)

**Comment by sobrinho** [comment]
@clemens I reviewed all PRs and commented, take a look when you can :)

**Comment by clemens** [comment]
All done. :) Thanks for your help, man!
